services:
  elysia_app:
    container_name: elysia_dev
    build: 
      context: .
      dockerfile: Dockerfile.test
    restart: always
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - DATABASE_HOST=database
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - nexus_network
    depends_on:
      database:
        condition: service_started
  
  database:
    container_name: db_postgis_dev
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgis_dev
    ports:
      - "5432:5432"
  
    networks:
      - nexus_network

volumes:
  db:

networks:
  nexus_network:
    driver: bridge